# Generated by Django 4.0.4 on 2022-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('invoice_delivery_period', models.DateField(blank=True, null=True)),
                ('invoice_date_sent', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vat_percentage', models.FloatField(blank=True, null=True)),
                ('vat', models.PositiveIntegerField(blank=True, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('number_of_units', models.FloatField(blank=True, null=True)),
                ('amount_per_unit_value', models.FloatField(blank=True, null=True)),
                ('amount_per_unit_currency', models.CharField(blank=True, max_length=4, null=True)),
                ('ledger_account_id', models.UUIDField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
