# Generated by Django 4.0.4 on 2022-05-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('invoice_delivery_period', models.DateField(blank=True, null=True)),
                ('invoice_date_sent', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('vat_percentage', models.FloatField(blank=True, null=True)),
                ('vat', models.PositiveIntegerField(blank=True, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('number_of_units', models.FloatField(blank=True, null=True)),
                ('amount_per_unit_value', models.FloatField(blank=True, null=True)),
                ('amount_per_unit_currency', models.CharField(blank=True, max_length=4, null=True)),
                ('ledger_account_id', models.UUIDField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
            ],
        ),
    ]
