# Generated by Django 4.0.4 on 2022-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.UUIDField(blank=True, default='JkVS3-pfHWyfn7qO86Sx0cEsH4Vj3vFV6oC_Y5e4gTs', null=True, unique=True),
        ),
    ]
