# Generated by Django 4.0.4 on 2022-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_accesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(blank=True, default='JkVS3-pfHWyfn7qO86Sx0cEsH4Vj3vFV6oC_Y5e4gTs', max_length=255, null=True),
        ),
    ]
